# Generated by Django 5.0.6 on 2024-06-15 20:10

import task_app.constants.choices
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0003_alter_category_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subtask',
            name='status',
            field=models.CharField(choices=task_app.constants.choices.StatusChoices.choices, default=task_app.constants.choices.StatusChoices['NEW'], max_length=20),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=task_app.constants.choices.StatusChoices.choices, default=task_app.constants.choices.StatusChoices['NEW'], max_length=20),
        ),
    ]
