# Generated by Django 5.0.6 on 2024-06-15 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0004_alter_subtask_status_alter_task_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name',)},
        ),
    ]
